remote_theme: pages-themes/midnight@v0.2.0 #minimal@v0.2.0 hacker@v0.2.0 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# GitHub Pages themes https://github.com/pages-themes
# minimal@v0.2.0
# cayman@v0.2.0
# hacker@v0.2.0
# architect@v0.2.0
# slate@v0.2.0
# midnight@v0.2.0

title: Value
description: α+β
show_downloads: false
logo: https://github.com/user-attachments/assets/5d1fd069-0616-49eb-a66a-43a8d2068207
#https://github.com/user-attachments/assets/bcc32321-0ca9-49ec-a795-fbbcc68841e5 
#https://github.com/user-attachments/assets/51c29f7f-01c6-42fb-8194-5b0ec4372f42


